name: pr-comment
description: pr-comment action that shows changes in PR
author: Alexisinho

# Define your inputs here.
inputs:
  owner:
    description: The owner of the repo (user or org)
    required: true
  repo: 
    description: The name of the repo
    required: true
  pr_number:
    description: The number of the PR
    required: true
  token:
    description: The token to authenticate to GitHub
    required: true

# Define your outputs here.
outputs:
  comment_body:
    description: The markdown body of the comment that was created

runs:
  using: node20
  main: dist/index.js
